### ISSUE TITLE
Add create post endpoint

### ISSUE THREAD

**Issue by ingeniumed** [Automattic/vip-block-data-api#38]
Add a POST endpoint that will create a post, and ensure that not everything goes into just a classic block. The idea is to have a way to migrate into the block editor, and be able to use this endpoint to create your posts without using the block editor.

There are some open ended questions such as:

- What's the format that we should expect?
- Do we have all the hooks/filters in place to support this functionality?

**Comment by ingeniumed** [comment]
Closing this off after internal discussion, can be revisited down the line.

**Comment by alecgeatches** [comment]
Adding a bit more context here on that internal discussion that lead us to drop the post create/write endpoint.

We created a prototype, but it had a few problems:

1. In order to serialize arbitrary blocks from JSON to HTML, we need to execute the React implementation of blocks' `save()` function and get the resulting markup.
2. Running arbitrary block `save()` functions requires two main things: a JavaScript runtime to run block React implementations, and access to the JavaScript files and libraries loaded by WordPress and plugins.
3. Gutenberg and WordPress plugins expect to run in a browser, e.g. utilizing browser-specific `document.*` and `window.*` methods. In order to load the context of WordPress and custom plugins, we needed to run our serialization code in a headless browser rather than a simpler `Node.js` instance alone.
4. Our final prototype used a REST API, which talked with a separate Node.js service, which used Puppeteer and headless Chrome to load WordPress in a browser, log-in and [execute the `serialize()` function](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-blocks/#serialize) for blocks in an editor window, and return the block markup to the REST API, which could then create a post. This implementation was bulky, slow, and had a complicated security model to allow Puppeteer to log-in.

While we were excited for the possibilities a create endpoint would open for Gutenberg content, the end result was too complex and had an iffy security model that was difficult to build a production service around. We would like to revisit this in the future and see if there's a better way at that time.
